<?php
 
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function lowercase_user__help($path, $arg) {
  switch ($path) {
    case "admin/help#lowercase_user":
      $output =  '<p>' . t("Lowercase User") . '</p>';
      $output .=  '<p>' . t("Enforce lowercase on all drupal user ids. Enabling the module will cause all user ids to be changed to lowercase on any user insert or user update.  Do not enable if you wish to keep older users as mixed case.") . '</p>';
      return $output;
      break;
  }
}

/**
 * Implements hook_menu().
 */
function lowercase_user_menu() {
  return array(
    'admin/lowercase_user/configure' => array(
      'title' => 'Lowercase User Configuration',
      'description' => 'Configure the Lowercase User Module.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('lowercase_user_admin_settings'),
      'access arguments' => array('administer site configuration'),
      'file' => 'lowercase_user.admin.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'lowercase_user' => array(
      'title' => 'Lowercase User Information',
      'description' => 'General Information Interface',
      'page callback' => 'lowercase_user_main',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_CALLBACK,
    ),
  );
}
/*
 * Performs the database change to the drupal users table
 */
function lowercase_user_run_now(){
  $the_update = db_update('users')
    ->expression('name', 'lower(name)')
    ->execute();
  return $the_update;

}
/*
 * lowercase_user menu item sent here.  Not much functionality at the moment
 */
function lowercase_user_main($one = ''){
  global $base_url;
  if ($one == 'db_run'){
    $the_update = lowercase_user_run_now();
    return t('Users updated:').$the_update;
  }  
  return l(t('Click to change users to lowercase now.'),$base_url.'/lowercase_user/db_run');
}
/*
 * hook_user_insert
 * Change all users to lowercase on any insert 
 */
function lowercase_user_user_insert(&$edit, $account, $category){
  lowercase_user_run_now();
}
/*
 * hook_user_update
 * Change all users to lowercase on any insert 
 */
function lowercase_user_user_update(&$edit, $account, $category){
  lowercase_user_run_now();
}
